### PR TITLE
Fixed parser to be compatible with new ua-parser

### PR DESCRIPTION
**Pull request by IMDagger**
"RT" and "ME" are stored in version now

### CODE REVIEW

**Comment by IMDagger** [comment]
didn't touch travis configuration, but I guess 3.3 (because pip doesn't work) should be removed from the list to pass checks

**Comment by selwin** [comment]
Sorry for the delayed response.

I have just updated travis.yml to support Python 2.7 and Python >= 3.4. Could you please merge the changes to this branch to see if the tests pass?

If we can get this in, I'll cut a release soon.

**Comment by IMDagger** [comment]
@selwin TravisCI said "3.7 is not installed; attempting download" this time and building was failed for 3.7 case (as for 3.3 previous time)

**Comment by selwin** [comment]
We should omit Python 3.7 then, let’s just test up to Python 3.6.

**Comment by IMDagger** [comment]
@selwin I suppose we can try this official workaround for [3.7](https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905)

**Comment by selwin** [comment]
Sure, let me know if it works :)

Best,
Selwin

**Comment by IMDagger** [comment]
> Sure, let me know if it works :) Best, Selwin
> […](#)
> On 31 Mar 2019 03.48 +0700, Alex Moiseenko ***@***.***>, wrote: @selwin I suppose we can try this official workaround for 3.7 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I just added "dist: xenial" and 3.7 works now

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
