### PR TITLE
Preserve minor and patch version even if they are zeros

### PR DESCRIPTION
**Pull request by uaymas**
The current logic drops the minor and patch version if they are zeros.

E.g. '10.0' becomes '10' and '5.0.0' becomes '5'

Those info are sometimes useful for doing version comparison

### CODE REVIEW

**Comment by HunjaeJung** [comment]
+1

**Comment by selwin** [comment]
@uaymas could you please fix the conflicts so I can merge this in?

**Comment by selwin** [comment]
@HunjaeJung please look at this when you can :)

**Comment by selwin** [comment]
Fixed in https://github.com/selwin/python-user-agents/commit/684a37c5ae89af010dfb2d7fe4d341207a461d2a . Please let me know if there's any issues.

**Pull request closed without merging**
