### PR TITLE
Add Chromebook detection as a "pc"

### PR DESCRIPTION
**Pull request by kulor**
Given Chromebooks are laptops, treat them as is done for MacBooks - "PC" category.

The new test for this passes but pre-existing test for iPad is failing.

### CODE REVIEW

**Comment by kulor** [comment]
@selwin any chance this could be reviewed or shall I work off my fork?

**Comment by selwin** [comment]
Thanks for the PR.

Could you please change the check for ChromeOS to look at `os.family` and not by checking the raw UA string?

**Comment by kulor** [comment]
@selwin done

**Comment by mihaibogdan10** [comment]
@selwin Are you going to merge this any time soon?

**Comment by asalant** [comment]
I'd love to see this merged too. Was just investigating how to make the patch myself then thought to see if someone else had done it already.

**Comment by selwin** [comment]
Thanks for the PR and sorry for the delay. Will try to tag a new release sometime in the next few days.

**Comment by asalant** [comment]
Hi, just checking in on timing for a release to get this great fix into the people's hands.

**Comment by selwin** [comment]
@asalant I just release version 1.1.0 on PyPI. Check it out and let me know if it works.

**Comment by asalant** [comment]
Thanks!

**Pull request merged**
