### PR TITLE
Support Nokia N9

### LINKED ISSUE #33: Failed to detect Nokia N9 browser
N9 browser should give `is_mobile = True`

Here is the UA string:

```
Mozilla/5.0 (MeeGo; NokiaN9) AppleWebKit/534.13 (KHTML, like Gecko) NokiaBrowser/8.5.0 Mobile Safari/534.13
```

### PR DESCRIPTION
**Pull request by hongquan**
This is to fix #33

### CODE REVIEW

**Comment by selwin** [comment]
If we do this, we'll then have to add every other Nokia device models into `MOBILE_DEVICE_FAMILIES` so I don't think this is a good idea. Is there anything else that we can use to identify this as a mobile device?

The existence of `NokiaBrowser` string in the user agent perhaps?

**Comment by hongquan** [comment]
Or `NokiaBrowser` and `Mobile`

**Comment by selwin** [comment]
Sounds good to me. Could you please update your PR?

**Comment by hongquan** [comment]
@selwin I updated the PR.

**Comment by selwin** [comment]
@hongquan thanks for the PR!

**Pull request merged**
